import Icons from "@repo/ui/icons";
import {
  AccountSetupTask,
  BookingBadgeStatus,
  BookingInformation,
  BookingType,
  ListingStatus,
  NotificationType,
  Notification,
  PaymentBadgeStatus,
  TopRatedVehicleType,
  TransactionOrigin,
  TransactionStatus,
  TransactionTableRow,
  TransactionType,
  NewBookingType,
} from "./types";

type OptionType = { option: string; value: string };

export const hostAppUrl = "http://host.muvment.ng";

export const popupNavItems = [
  {
    icon: Icons.ic_globe_search,
    name: "Explore",
    link: "/explore/results",
    border: true,
  },
  {
    icon: Icons.ic_card_payment_confirmed,
    name: "Payments",
    link: "/transactions",
    border: false,
  },
  {
    icon: Icons.ic_booking_checked,
    name: "My Bookings",
    link: "/bookings",
    border: false,
  },
  {
    icon: Icons.ic_whishlist,
    name: "Favorites",
    link: "/favorites",
    border: true,
  },
  {
    icon: Icons.ic_user_account,
    name: "Accounts",
    link: "/account",
    border: false,
  },
  {
    icon: Icons.ic_notification,
    name: "Notifications",
    link: "/notifications",
    border: false,
  },
  {
    icon: Icons.ic_gift,
    name: "Refer A Friend",
    link: "/account?tab=referrals",
    border: true,
  },
  /*   {
    icon: Icons.ic_help_circle,
    name: "How Muvment works",
    link: "/how-it-works",
    border: false,
  }, */
  /*   {
    icon: Icons.ic_support,
    name: "Get Help",
    link: "/get-help",
    border: false,
  }, */

  {
    icon: Icons.ic_logout,
    name: "Log out",
    border: false,
  },
];

export const popupNavItemsforNoUser = [
  {
    icon: Icons.ic_login,
    name: "Login",
    link: "/login",
  },
  {
    icon: Icons.ic_host,
    name: "Sign Up",
    link: "/signup",
  },

  /*   {
    icon: Icons.ic_help_circle,
    name: "How Muvment works",
    link: "/",
  }, */
  /*   {
    icon: Icons.ic_support,
    name: "Get Help",
    link: "/",
  }, */
];

const currentYear = new Date().getFullYear();

// explore vehicles
export const yearsFilterArray = Array.from(
  { length: currentYear - 2010 + 1 },
  (_, index) => (2010 + index).toString()
);

export const vehicleTypeArray: string[] = [
  "sedan",
  "suv",
  "truck",
  "sportsCar",
  "pickup",
  "bus",
  "luxuryVehicle",
  "hatchback",
  "coupe",
  "minivan",
  "electricVehicle",
  "hybridVehicle",
  "car",
  "stationWagon",
  "van",
  "off-roadVehicle",
  "motorcycle",
  "all-terrainVehicle",
];

export const vehicleMakeArray = [
  "acura",
  "alfaRomeo",
  "astonMartin",
  "audi",
  "abarth",
  "aixam",
  "ariel",
  "arrinera",
  "arcfox",
  "bentley",
  "bmw",
  "buick",
  "bugatti",
  "byd",
  "borgward",
  "baojun",
  "brabus",
  "bristol",
  "byton",
  "cadillac",
  "chevrolet",
  "chrysler",
  "citroen",
  "cupra",
  "caterham",
  "chery",
  "cizeta",
  "covini",
  "canoo",
  "dacia",
  "daewoo",
  "daihatsu",
  "dodge",
  "dongfeng",
  "deTomaso",
  "delorean",
  "drako",
  "exeed",
  "eagle",
  "edisonMotors",
  "ferrari",
  "fiat",
  "ford",
  "fisker",
  "faw",
  "faradayFuture",
  "ginetta",
  "gillet",
  "gonow",
  "gacMotor",
  "genesis",
  "gmc",
  "greatWall",
  "haval",
  "hispanoSuiza",
  "hongqi",
  "holden",
  "honda",
  "hyundai",
  "hummer",
  "infiniti",
  "isuzu",
  "iveco",
  "italdesign",
  "irizar",
  "jaguar",
  "jeep",
  "jacMotors",
  "jensen",
  "jetta",
  "karma",
  "kenworth",
  "kia",
  "koenigsegg",
  "lamborghini",
  "landRover",
  "lexus",
  "lincoln",
  "lotus",
  "lancia",
  "lucidMotors",
  "lynk&Co",
  "localMotors",
  "maserati",
  "mazda",
  "mclaren",
  "mercedesBenz",
  "mini",
  "mitsubishi",
  "mahindra",
  "mg",
  "man",
  "morgan",
  "maybach",
  "nio",
  "nissan",
  "noble",
  "neoplan",
  "opel",
  "osi",
  "ora",
  "oldsmobile",
  "pagani",
  "pininfarina",
  "perodua",
  "proton",
  "polestar",
  "peugeot",
  "porsche",
  "ram",
  "renault",
  "rollsRoyce",
  "rivian",
  "rimac",
  "rezvani",
  "rossion",
  "roewe",
  "saab",
  "seat",
  "subaru",
  "suzuki",
  "skoda",
  "spyker",
  "ssangYong",
  "saleen",
  "srt",
  "tesla",
  "toyota",
  "tata",
  "troller",
  "techrules",
  "tvr",
  "thunderPower",
  "ultima",
  "uaz",
  "uniti",
  "venturi",
  "vector",
  "vinFast",
  "volkswagen",
  "volvo",
  "vauxhall",
  "wiesmann",
  "wuling",
  "workhorse",
  "zastava",
  "zaz",
  "zenos",
  "zhongtong",
  "zenvo",
  "zagato",
];

// vehicle booking
export const yearOfReleaseOptions = Array.from(
  { length: currentYear - 2010 + 1 },
  (_, index) => ({
    value: (2010 + index).toString(),
    option: (2010 + index).toString(),
  })
);

export const vehicleTypesOptions: OptionType[] = [
  { value: "Sedan", option: "Sedan" },
  { value: "SUV", option: "SUV" },
  { value: "Truck", option: "Truck" },
  { value: "Sports Car", option: "Sports Car" },
  { value: "Pickup", option: "Pickup" },
  { value: "Bus", option: "Bus" },
  { value: "Luxury Vehicle", option: "Luxury Vehicle" },
  { value: "Hatchback", option: "Hatchback" },
  { value: "Coupe", option: "Coupe" },
  { value: "Minivan", option: "Minivan" },
  { value: "Electric vehicle", option: "Electric vehicle" },
  { value: "Hybrid vehicle", option: "Hybrid vehicle" },
  { value: "Car", option: "Car" },
  { value: "Station wagon", option: "Station wagon" },
  { value: "Van", option: "Van" },
  { value: "Off-road vehicle", option: "Off-road vehicle" },
  { value: "Motorcycle", option: "Motorcycle" },
  { value: "All-terrain vehicle", option: "All-terrain vehicle" },
];

export const vehicleMakesOptions: OptionType[] = [
  { value: "Acura", option: "Acura" },
  { value: "Alfa Romeo", option: "Alfa Romeo" },
  { value: "Aston Martin", option: "Aston Martin" },
  { value: "Audi", option: "Audi" },
  { value: "Abarth", option: "Abarth" },
  { value: "Aixam", option: "Aixam" },
  { value: "Ariel", option: "Ariel" },
  { value: "Arrinera", option: "Arrinera" },
  { value: "Arcfox", option: "Arcfox" },
  { value: "Bentley", option: "Bentley" },
  { value: "BMW", option: "BMW" },
  { value: "Buick", option: "Buick" },
  { value: "Bugatti", option: "Bugatti" },
  { value: "BYD", option: "BYD" },
  { value: "Borgward", option: "Borgward" },
  { value: "Baojun", option: "Baojun" },
  { value: "Brabus", option: "Brabus" },
  { value: "Bristol", option: "Bristol" },
  { value: "BYTON", option: "BYTON" },
  { value: "Cadillac", option: "Cadillac" },
  { value: "Chevrolet", option: "Chevrolet" },
  { value: "Chrysler", option: "Chrysler" },
  { value: "Citroën", option: "Citroën" },
  { value: "Cupra", option: "Cupra" },
  { value: "Caterham", option: "Caterham" },
  { value: "Chery", option: "Chery" },
  { value: "Cizeta", option: "Cizeta" },
  { value: "Covini", option: "Covini" },
  { value: "Canoo", option: "Canoo" },
  { value: "Dacia", option: "Dacia" },
  { value: "Daewoo", option: "Daewoo" },
  { value: "Daihatsu", option: "Daihatsu" },
  { value: "Dodge", option: "Dodge" },
  { value: "Dongfeng", option: "Dongfeng" },
  { value: "De Tomaso", option: "De Tomaso" },
  { value: "Delorean", option: "Delorean" },
  { value: "Drako", option: "Drako" },
  { value: "Exeed", option: "Exeed" },
  { value: "Eagle", option: "Eagle" },
  { value: "Edison Motors", option: "Edison Motors" },
  { value: "Ferrari", option: "Ferrari" },
  { value: "Fiat", option: "Fiat" },
  { value: "Ford", option: "Ford" },
  { value: "Fisker", option: "Fisker" },
  { value: "FAW", option: "FAW" },
  { value: "Faraday Future", option: "Faraday Future" },
  { value: "Ginetta", option: "Ginetta" },
  { value: "Gillet", option: "Gillet" },
  { value: "Gonow", option: "Gonow" },
  { value: "GAC Motor", option: "GAC Motor" },
  { value: "Genesis", option: "Genesis" },
  { value: "GMC", option: "GMC" },
  { value: "Great Wall", option: "Great Wall" },
  { value: "Haval", option: "Haval" },
  { value: "Hispano-Suiza", option: "Hispano-Suiza" },
  { value: "Hongqi", option: "Hongqi" },
  { value: "Holden", option: "Holden" },
  { value: "Honda", option: "Honda" },
  { value: "Hyundai", option: "Hyundai" },
  { value: "Hummer", option: "Hummer" },
  { value: "Infiniti", option: "Infiniti" },
  { value: "Isuzu", option: "Isuzu" },
  { value: "Iveco", option: "Iveco" },
  { value: "Italdesign", option: "Italdesign" },
  { value: "Irizar", option: "Irizar" },
  { value: "Jaguar", option: "Jaguar" },
  { value: "Jeep", option: "Jeep" },
  { value: "JAC Motors", option: "JAC Motors" },
  { value: "Jensen", option: "Jensen" },
  { value: "Jetta", option: "Jetta" },
  { value: "Karma", option: "Karma" },
  { value: "Kenworth", option: "Kenworth" },
  { value: "Kia", option: "Kia" },
  { value: "Koenigsegg", option: "Koenigsegg" },
  { value: "Lamborghini", option: "Lamborghini" },
  { value: "Land Rover", option: "Land Rover" },
  { value: "Lexus", option: "Lexus" },
  { value: "Lincoln", option: "Lincoln" },
  { value: "Lotus", option: "Lotus" },
  { value: "Lancia", option: "Lancia" },
  { value: "Lucid Motors", option: "Lucid Motors" },
  { value: "Lynk & Co", option: "Lynk & Co" },
  { value: "Local Motors", option: "Local Motors" },
  { value: "Maserati", option: "Maserati" },
  { value: "Mazda", option: "Mazda" },
  { value: "McLaren", option: "McLaren" },
  { value: "Mercedes-Benz", option: "Mercedes-Benz" },
  { value: "Mini", option: "Mini" },
  { value: "Mitsubishi", option: "Mitsubishi" },
  { value: "Mahindra", option: "Mahindra" },
  { value: "MG", option: "MG" },
  { value: "MAN", option: "MAN" },
  { value: "Morgan", option: "Morgan" },
  { value: "Maybach", option: "Maybach" },
  { value: "Nio", option: "Nio" },
  { value: "Nissan", option: "Nissan" },
  { value: "Noble", option: "Noble" },
  { value: "Neoplan", option: "Neoplan" },
  { value: "Opel", option: "Opel" },
  { value: "OSI", option: "OSI" },
  { value: "Ora", option: "Ora" },
  { value: "Oldsmobile", option: "Oldsmobile" },
  { value: "Pagani", option: "Pagani" },
  { value: "Pininfarina", option: "Pininfarina" },
  { value: "Perodua", option: "Perodua" },
  { value: "Proton", option: "Proton" },
  { value: "Polestar", option: "Polestar" },
  { value: "Peugeot", option: "Peugeot" },
  { value: "Porsche", option: "Porsche" },
  { value: "Ram", option: "Ram" },
  { value: "Renault", option: "Renault" },
  { value: "Rolls-Royce", option: "Rolls-Royce" },
  { value: "Rivian", option: "Rivian" },
  { value: "Rimac", option: "Rimac" },
  { value: "Rezvani", option: "Rezvani" },
  { value: "Rossion", option: "Rossion" },
  { value: "Roewe", option: "Roewe" },
  { value: "Saab", option: "Saab" },
  { value: "Seat", option: "Seat" },
  { value: "Subaru", option: "Subaru" },
  { value: "Suzuki", option: "Suzuki" },
  { value: "Skoda", option: "Skoda" },
  { value: "Spyker", option: "Spyker" },
  { value: "SsangYong", option: "SsangYong" },
  { value: "Saleen", option: "Saleen" },
  { value: "SRT", option: "SRT" },
  { value: "Tesla", option: "Tesla" },
  { value: "Toyota", option: "Toyota" },
  { value: "Tata", option: "Tata" },
  { value: "Troller", option: "Troller" },
  { value: "Techrules", option: "Techrules" },
  { value: "TVR", option: "TVR" },
  { value: "Thunder Power", option: "Thunder Power" },
  { value: "Ultima", option: "Ultima" },
  { value: "UAZ", option: "UAZ" },
  { value: "Uniti", option: "Uniti" },
  { value: "Venturi", option: "Venturi" },
  { value: "Vector", option: "Vector" },
  { value: "VinFast", option: "VinFast" },
  { value: "Volkswagen", option: "Volkswagen" },
  { value: "Volvo", option: "Volvo" },
  { value: "Vauxhall", option: "Vauxhall" },
  { value: "VinFast", option: "VinFast" },
  { value: "Wiesmann", option: "Wiesmann" },
  { value: "Wuling", option: "Wuling" },
  { value: "Workhorse", option: "Workhorse" },
  { value: "Zastava", option: "Zastava" },
  { value: "ZAZ", option: "ZAZ" },
  { value: "Zenos", option: "Zenos" },
  { value: "Zhongtong", option: "Zhongtong" },
  { value: "Zenvo", option: "Zenvo" },
  { value: "Zagato", option: "Zagato" },
];

export const vehicleModelsOptions: OptionType[] = [
  { value: "124 Spider", option: "124 Spider" },
  { value: "1500", option: "1500" },
  { value: "2500", option: "2500" },
  { value: "300", option: "300" },
  { value: "3500", option: "3500" },
  { value: "3 Series", option: "3 Series" },
  { value: "4C", option: "4C" },
  { value: "488 GTB", option: "488 GTB" },
  { value: "5 Series", option: "5 Series" },
  { value: "570S", option: "570S" },
  { value: "570X", option: "570X" },
  { value: "720S", option: "720S" },
  { value: "7 Series", option: "7 Series" },
  { value: "812 Superfast", option: "812 Superfast" },
  { value: "A3", option: "A3" },
  { value: "A4", option: "A4" },
  { value: "A6", option: "A6" },
  { value: "A-Class", option: "A-Class" },
  { value: "Accord", option: "Accord" },
  { value: "Acadia", option: "Acadia" },
  { value: "Altima", option: "Altima" },
  { value: "Atlas", option: "Atlas" },
  { value: "ATS", option: "ATS" },
  { value: "Aviator", option: "Aviator" },
  { value: "Aventador", option: "Aventador" },
  { value: "Bentayga", option: "Bentayga" },
  { value: "Berlingo", option: "Berlingo" },
  { value: "Bronco", option: "Bronco" },
  { value: "Bronco Sport", option: "Bronco Sport" },
  { value: "Camaro", option: "Camaro" },
  { value: "Camry", option: "Camry" },
  { value: "Captur", option: "Captur" },
  { value: "Cayenne", option: "Cayenne" },
  { value: "Challenger", option: "Challenger" },
  { value: "Charger", option: "Charger" },
  { value: "Chiron", option: "Chiron" },
  { value: "Civic", option: "Civic" },
  { value: "Clio", option: "Clio" },
  { value: "Compass", option: "Compass" },
  { value: "Continental", option: "Continental" },
  { value: "Continental GT", option: "Continental GT" },
  { value: "Cooper", option: "Cooper" },
  { value: "Corolla", option: "Corolla" },
  { value: "Corsair", option: "Corsair" },
  { value: "Countryman", option: "Countryman" },
  { value: "Crosstrek", option: "Crosstrek" },
  { value: "CR-V", option: "CR-V" },
  { value: "Cullinan", option: "Cullinan" },
  { value: "CX-5", option: "CX-5" },
  { value: "CX-9", option: "CX-9" },
  { value: "Divo", option: "Divo" },
  { value: "Discovery", option: "Discovery" },
  { value: "Discovery Sport", option: "Discovery Sport" },
  { value: "Duster", option: "Duster" },
  { value: "Durango", option: "Durango" },
  { value: "Eclipse Cross", option: "Eclipse Cross" },
  { value: "Elise", option: "Elise" },
  { value: "Elantra", option: "Elantra" },
  { value: "Encore", option: "Encore" },
  { value: "Enclave", option: "Enclave" },
  { value: "Equinox", option: "Equinox" },
  { value: "Escape", option: "Escape" },
  { value: "Escalade", option: "Escalade" },
  { value: "E-Class", option: "E-Class" },
  { value: "ES", option: "ES" },
  { value: "Evoque", option: "Evoque" },
  { value: "Evora", option: "Evora" },
  { value: "Expedition", option: "Expedition" },
  { value: "Explorer", option: "Explorer" },
  { value: "F-150", option: "F-150" },
  { value: "F8 Tributo", option: "F8 Tributo" },
  { value: "F-Pace", option: "F-Pace" },
  { value: "Fiesta", option: "Fiesta" },
  { value: "Fit", option: "Fit" },
  { value: "Focus", option: "Focus" },
  { value: "Forester", option: "Forester" },
  { value: "Formentor", option: "Formentor" },
  { value: "Flying Spur", option: "Flying Spur" },
  { value: "Genesis G70", option: "Genesis G70" },
  { value: "Genesis G80", option: "Genesis G80" },
  { value: "Genesis G90", option: "Genesis G90" },
  { value: "Gladiator", option: "Gladiator" },
  { value: "Ghost", option: "Ghost" },
  { value: "Giulia", option: "Giulia" },
  { value: "Ghibli", option: "Ghibli" },
  { value: "GLC", option: "GLC" },
  { value: "GL-Class", option: "GL-Class" },
  { value: "GLS", option: "GLS" },
  { value: "Golf", option: "Golf" },
  { value: "GranTurismo", option: "GranTurismo" },
  { value: "Grand Cherokee", option: "Grand Cherokee" },
  { value: "GT", option: "GT" },
  { value: "GT-R", option: "GT-R" },
  { value: "G-Wagen", option: "G-Wagen" },
  { value: "GX", option: "GX" },
  { value: "Highlander", option: "Highlander" },
  { value: "Huracan", option: "Huracan" },
  { value: "ILX", option: "ILX" },
  { value: "Impreza", option: "Impreza" },
  { value: "I-Pace", option: "I-Pace" },
  { value: "IS", option: "IS" },
  { value: "Jetta", option: "Jetta" },
  { value: "Jimny", option: "Jimny" },
  { value: "Journey", option: "Journey" },
  { value: "Koleos", option: "Koleos" },
  { value: "Kona", option: "Kona" },
  { value: "LaCrosse", option: "LaCrosse" },
  { value: "Levante", option: "Levante" },
  { value: "Lincoln Navigator", option: "Lincoln Navigator" },
  { value: "Logan", option: "Logan" },
  { value: "LS", option: "LS" },
  { value: "LX", option: "LX" },
  { value: "M3", option: "M3" },
  { value: "Macan", option: "Macan" },
  { value: "Maxima", option: "Maxima" },
  { value: "Mazda3", option: "Mazda3" },
  { value: "Mazda6", option: "Mazda6" },
  { value: "MDX", option: "MDX" },
  { value: "Megane", option: "Megane" },
  { value: "Model 3", option: "Model 3" },
  { value: "Model S", option: "Model S" },
  { value: "Model X", option: "Model X" },
  { value: "Model Y", option: "Model Y" },
  { value: "Mulsanne", option: "Mulsanne" },
  { value: "Murano", option: "Murano" },
  { value: "Mustang", option: "Mustang" },
  { value: "MX-5 Miata", option: "MX-5 Miata" },
  { value: "Navigator", option: "Navigator" },
  { value: "NSX", option: "NSX" },
  { value: "Odyssey", option: "Odyssey" },
  { value: "Outback", option: "Outback" },
  { value: "Outlander", option: "Outlander" },
  { value: "Pacifica", option: "Pacifica" },
  { value: "Panamera", option: "Panamera" },
  { value: "Panda", option: "Panda" },
  { value: "Passat", option: "Passat" },
  { value: "Patriot", option: "Patriot" },
  { value: "Phantom", option: "Phantom" },
  { value: "Pilot", option: "Pilot" },
  { value: "Portofino", option: "Portofino" },
  { value: "Q5", option: "Q5" },
  { value: "Q7", option: "Q7" },
  { value: "Q50", option: "Q50" },
  { value: "Q60", option: "Q60" },
  { value: "Quattroporte", option: "Quattroporte" },
  { value: "R8", option: "R8" },
  { value: "RAV4", option: "RAV4" },
  { value: "RDX", option: "RDX" },
  { value: "Regal", option: "Regal" },
  { value: "Renegade", option: "Renegade" },
  { value: "Rexton", option: "Rexton" },
  { value: "Rogue", option: "Rogue" },
  { value: "Roma", option: "Roma" },
  { value: "RS7", option: "RS7" },
  { value: "S-Class", option: "S-Class" },
  { value: "Sandero", option: "Sandero" },
  { value: "Santa Fe", option: "Santa Fe" },
  { value: "Seltos", option: "Seltos" },
  { value: "Senna", option: "Senna" },
  { value: "S60", option: "S60" },
  { value: "Silverado", option: "Silverado" },
  { value: "Sierra", option: "Sierra" },
  { value: "Sonata", option: "Sonata" },
  { value: "Soul", option: "Soul" },
  { value: "Sportage", option: "Sportage" },
  { value: "Stinger", option: "Stinger" },
  { value: "Suburban", option: "Suburban" },
  { value: "Swift", option: "Swift" },
  { value: "Tacoma", option: "Tacoma" },
  { value: "Tahoe", option: "Tahoe" },
  { value: "Taycan", option: "Taycan" },
  { value: "Telluride", option: "Telluride" },
  { value: "Tiguan", option: "Tiguan" },
  { value: "TLX", option: "TLX" },
  { value: "Tucson", option: "Tucson" },
  { value: "Tundra", option: "Tundra" },
  { value: "TT", option: "TT" },
  { value: "Type R", option: "Type R" },
  { value: "Urus", option: "Urus" },
  { value: "V90", option: "V90" },
  { value: "V8 Vantage", option: "V8 Vantage" },
  { value: "Vantage", option: "Vantage" },
  { value: "V60", option: "V60" },
  { value: "Veyron", option: "Veyron" },
  { value: "Vitara", option: "Vitara" },
  { value: "Voyager", option: "Voyager" },
  { value: "Wraith", option: "Wraith" },
  { value: "WRX", option: "WRX" },
  { value: "X3", option: "X3" },
  { value: "X5", option: "X5" },
  { value: "XC60", option: "XC60" },
  { value: "XC90", option: "XC90" },
  { value: "Yukon", option: "Yukon" },
  { value: "Z4", option: "Z4" },
];

export const vehicleColorsOptions: OptionType[] = [
  { value: "Red", option: "Red" },
  { value: "Black", option: "Black" },
  { value: "White", option: "White" },
  { value: "Silver", option: "Silver" },
  { value: "Gold", option: "Gold" },
];

export const vehicleFeaturesOptions: string[] = [
  "AllWheelDrive",
  "AndroidAuto",
  "AppleCarPlay",
  "AuxInput",
  "BackupCamera",
  "BikeRack",
  "BlindSpotWarning",
  "Bluetooth",
  "ChildSeat",
  "Convertible",
  "Gps",
  "HeatedSeats",
  "KeylessEntry",
  "PetFriendly",
  "SkiRack",
  "UsbCharger",
  "Sunroof",
  "TollPass",
  "UsbInput",
  "WheelchairAccessible",
];

export const citiesOptions: OptionType[] = [
  { value: "Abuja", option: "Abuja" },
  { value: "Accra", option: "Accra" },
  { value: "Benin", option: "Benin City" },
  { value: "Enugu", option: "Enugu" },
  { value: "Lagos", option: "Lagos" },
  { value: "Port Harcourt", option: "Port Harcourt" },
];

export const yesOrNoOptions: OptionType[] = [
  { value: "yes", option: "Yes" },
  { value: "no", option: "No" },
];

export const vehicleAvailabilityOptions: OptionType[] = [
  { value: "1 day", option: "1 day" },
  { value: "2 days", option: "2 days" },
  { value: "3 days", option: "3 days" },
  { value: "4 days", option: "4 days" },
  { value: "5 days", option: "5 days" },
  { value: "6 days", option: "6 days" },

  { value: "1 week", option: "1 week" },
  { value: "2 weeks", option: "2 weeks" },
  { value: "3 weeks", option: "3 weeks" },
  { value: "4 weeks", option: "4 weeks" },
];

export const tripPurposeOptions: OptionType[] = [
  { option: "Business Trip", value: "Business Trip" },
  { option: "Leisure", value: "Leisure" },
  { option: "Event", value: "Event" },
  { option: "Airport Transfer", value: "Airport Transfer" },
  { option: "Vacation", value: "Vacation" },
  { option: "School Pickup", value: "School Pickup" },
  { option: "City Tour", value: "City Tour" },
  { option: "Relocation", value: "Relocation" },
  { option: "Corporate Use", value: "Corporate Use" },
  { option: "Emergency", value: "Emergency" },
  { option: "Charity", value: "Charity" },
  { option: "Film/Photography Shoot", value: "Film/Photography Shoot" },
  { option: "Test Drive", value: "Test Drive" },
  { option: "Daily Commute", value: "Daily Commute" },
  { option: "Special Delivery", value: "Special Delivery" },
  { option: "Shopping", value: "Shopping" },
  { option: "Errands", value: "Errands" },
  { option: "Adventure", value: "Adventure" },
  { option: "VIP/High-Class Transport", value: "VIP/High-Class Transport" },
  {
    option: "Fleet Addition for Business",
    value: "Fleet Addition for Business",
  },
  { option: "Family Trip", value: "Family Trip" },
];

export const outskirtsLocationOptions: string[] = [
  "Ikorodu",
  "Badagry",
  "Epe",
  "Ibeju-Lekki",
  "Ojo",
  "Alimosho",
  "Agege",
  "Ajah",
  "Agbara",
  "Sango",
  "Ijede",
  "Ikotun",
  "Egbeda",
];

export const daysOfTheWeek: string[] = [
  "sunday",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
];

export const monthsFilter: string[] = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const photoUploadTips = [
  {
    title: "Take Photos From Different Angles",
    description:
      "Show all sides of your car - front, back, sides, and at an angle. Try to take photos during the day when there’s plenty of light, but avoid direct sunlight that can cause harsh shadows.",
  },
  {
    title: "Capture the Car's Condition",
    description:
      "Make sure your photos reflect the current condition of your car. Honesty builds trust with potential renters. If there are any minor dings or scratches, include a photo so there are no surprises.",
  },

  {
    title: "Mind the Weather",
    description:
      "Avoid taking photos on rainy or gloomy days. Sunshine makes everything look better. If the weather isn’t cooperating, wait for a better day to take your pictures.",
  },
  {
    title: "Clean Your Car Before the Photoshoot",
    description:
      "A clean car looks more inviting. Take the time to wash and vacuum your car before taking photos. This makes a big difference in how your car is perceived.",
  },
  {
    title: "Show Off the Interior and Exterior",
    description:
      "Renters want to see both the inside and outside of your car. Make sure to include shots of the dashboard, seats, trunk space, and any cool features like a sunroof or navigation system.",
  },
  {
    title: "Highlight Unique Features",
    description:
      "Got a great sound system or custom rims? Make sure to capture these unique features in your photos. They can make your car more appealing to potential renters.View detailed guidelines.",
  },
  {
    title: "Highlight Unique Features",
    description:
      "Got a great sound system or custom rims? Make sure to capture these unique features in your photos. They can make your car more appealing to potential renters.View detailed guidelines.",
  },
];

export const bookingOverviewTableHeadItems: string[] = [
  "Vehicle",
  "Guest Name",
  "Booking ID",
  "Booking Type",
  "Duration",
  "Start Date",
  "End Date",
  "Status",
  "Price",
  "Actions",
];

export const bookingAnalyticsTableHeadItems: string[] = [
  "Booking ID",
  "Status",
  "Booking Date",
  "Booking Type",
  "Duration",
  "Start Date",
  "End Date",
  "Amount",
  "Actions",
];

export const transactionTableHeadItems: string[] = [
  "Transaction ID",
  "Date",
  "Booking ID",
  "Vehicle",
  "Amount",
  "Payment Method",
  "Status",
  "Actions",
];

export const referralTableHeadItems: string[] = [
  "Name",
  "Email",
  "Date",
  "Status",
];

// ======================== Page Filters ======================== //
export const listingFilters = [
  {
    title: "status",
    options: [
      { option: "Review", value: ListingStatus.REVIEW },
      { option: "Feedback", value: ListingStatus.FEEDBACK },
      { option: "Accepted", value: ListingStatus.ACCEPTED },
      { option: "Rejected", value: ListingStatus.REJECTED },
      { option: "Suspended", value: ListingStatus.SUSPENDED },
    ],
  },
  {
    title: "type",
    options: vehicleTypesOptions,
  },
  {
    title: "location",
    options: citiesOptions,
  },
];

export const bookingOverviewFilters: {
  title: string;
  options: OptionType[];
}[] = [
  // {
  //   title: "bookingType",
  //   options: [
  //     { option: "Daily rides", value: "daily" },
  //     { option: "Interstate rides", value: "interstate" },
  //     { option: "Weekly rides", value: "weekly" },
  //     { option: "Monthly rides", value: "monthly" },
  //     { option: "Airport pickups", value: "airport" },
  //   ],
  // },
  {
    title: "bookingType",
    options: [
      { option: "Single day rides", value: BookingType.SINGLE_DAY },
      { option: "Multi day rides", value: BookingType.MULTI_DAY },
    ],
  },
];

// add type
export const bookingFilters = [
  {
    title: "bookingType",
    options: [
      { option: "1 Hour", value: NewBookingType.AN_HOUR },
      { option: "3 Hours", value: NewBookingType.THREE_HOURS },
      { option: "6 Hours", value: NewBookingType.SIX_HOURS },
      { option: "12 Hours", value: NewBookingType.TWELVE_HOURS },
      { option: "Airport Pickup", value: NewBookingType.AIRPORT_PICKUP },
    ],
  },
  {
    title: "status",
    options: [
      { option: "Pending", value: BookingBadgeStatus.PENDING },
      { option: "Completed", value: BookingBadgeStatus.COMPLTETED },
      { option: "Approved", value: BookingBadgeStatus.APPROVED },
      { option: "Cancelled", value: BookingBadgeStatus.CANCELLED },
    ],
  },
];

// add type
export const transactionFilters = [
  // {
  //   title: "type",
  //   options: [
  //     { option: "Credit", value: TransactionType.CREDIT },
  //     { option: "Debit", value: TransactionType.DEBIT },
  //   ],
  // },
  {
    title: "status",
    options: [
      { option: "Successful", value: TransactionStatus.SUCCESS },
      { option: "Pending", value: TransactionStatus.PENDING },
      { option: "Failed", value: TransactionStatus.FAILED },
    ],
  },
  // {
  //   title: "purpose",
  //   options: [
  //     { option: "Booking", value: TransactionOrigin.BOOKING },
  //     { option: "Withdrawal", value: TransactionOrigin.WITHDRAWAL },
  //   ],
  // },
];

// =================== mock data ===================//
export const topRatedVehicle: TopRatedVehicleType = {
  make: "Hyundai",
  model: "Tuscon",
  year: "2018",
  colour: "Black",
  seatingCapacity: "4",
  totalRides: "440",
  totalEarnings: "$330,000",
};

export const transactionData: TransactionTableRow[] = [
  {
    transactionId: "TXN-2023-01-1234",
    date: "Apr 12, 2023 | 09:32AM",
    bookingId: "BKG-1234-AB56",
    type: "Credit",
    vehicle: "Toyota Camry 2021",
    purpose: "Rental",
    amount: "NGN 100,000",
    status: "Successful",
    actions: "",
  },
  {
    transactionId: "TXN-2023-01-1234",
    date: "Apr 12, 2023 | 09:32AM",
    bookingId: "BKG-1234-AB56",
    type: "Debit",
    vehicle: "Toyota Camry 2021",
    purpose: "Rental",
    amount: "NGN 100,000",
    status: "Pending",
    actions: "",
  },
  {
    transactionId: "TXN-2023-01-1234",
    date: "Apr 12, 2023 | 09:32AM",
    bookingId: "BKG-1234-AB56",
    type: "Payout",
    vehicle: "Toyota Camry 2021",
    purpose: "Rental",
    amount: "NGN 100,000",
    status: "Failed",
    actions: "",
  },
];
