import { BookingOverviewTableRow, TopRatedVehicleType } from "./types";

export const monthsFilter = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const tableHeadItems = [
  "Vehicle",
  "Guest Name",
  "Booking ID",
  "Booking Type",
  "Duration",
  "Start Date",
  "End Date",
  "Status",
  "Price",
  "Actions",
];

// =================== mock data ===================//
export const topRatedVehicle: TopRatedVehicleType = {
  make: "Hyundai",
  model: "Tuscon",
  year: "2018",
  colour: "Black",
  seatingCapacity: "4",
  totalRides: "440",
  totalEarnings: "$330,000",
};

export const bookingOverviewTableItems: BookingOverviewTableRow[] = [
  {
    vehicle: "Toyota Camry 2021",
    guestName: "Chioma Nwosu",
    bookingId: "BKG-1234-AB56",
    bookingType: "Instant",
    duration: "Leading text",
    startDate: "Apr 12, 2023",
    endDate: "Apr 12, 2023",
    status: "Accepted",
    price: "NGN 100,000",
    actions: "Leading text",
  },
  {
    vehicle: "Honda Civic 2019",
    guestName: "Oluwaseun Ojo",
    bookingId: "BKG-4567-GH12",
    bookingType: "Leading text",
    duration: "1 day",
    startDate: "Apr 12, 2023",
    endDate: "Leading text",
    status: "Accepted",
    price: "Leading text",
    actions: "Leading text",
  },
  {
    vehicle: "Mercedes-Benz C-Class 2019",
    guestName: "Chukwuemeka Okeke",
    bookingId: "BKG-4567-GH12",
    bookingType: "Pick-up & drop-off",
    duration: "3 days",
    startDate: "Apr 11, 2023",
    endDate: "Leading text",
    status: "Accepted",
    price: "NGN 20,000",
    actions: "Leading text",
  },
  {
    vehicle: "Subaru Outback 2020",
    guestName: "Chigozie Nnamani",
    bookingId: "BKG-5678-IJ34",
    bookingType: "Long term",
    duration: "1 week",
    startDate: "Apr 11, 2023",
    endDate: "Leading text",
    status: "Accepted",
    price: "NGN 14,000",
    actions: "Leading text",
  },
  {
    vehicle: "Toyota Camry 2021",
    guestName: "Ezinne Chukwu",
    bookingId: "BKG-8901-MN78",
    bookingType: "Long term",
    duration: "Leading text",
    startDate: "Apr 10, 2023",
    endDate: "Apr 10, 2023",
    status: "Accepted",
    price: "NGN 30,000",
    actions: "Leading text",
  },
  {
    vehicle: "Mercedes-Benz C-Class 2019",
    guestName: "Oluchi Eze",
    bookingId: "BKG-0123-QR12",
    bookingType: "Instant",
    duration: "Leading text",
    startDate: "Apr 09, 2023",
    endDate: "Apr 09, 2023",
    status: "Accepted",
    price: "NGN 16,000",
    actions: "Leading text",
  },
  {
    vehicle: "Toyota Camry 2021",
    guestName: "Chika Ibe",
    bookingId: "BKG-3456-EF90",
    bookingType: "Instant",
    duration: "1 day",
    startDate: "Apr 09, 2023",
    endDate: "Leading text",
    status: "Accepted",
    price: "NGN 42,000",
    actions: "Leading text",
  },
  {
    vehicle: "Toyota Camry 2021",
    guestName: "Nnamdi Kalu",
    bookingId: "BKG-4567-GH12",
    bookingType: "Pick-up & drop-off",
    duration: "Leading text",
    startDate: "Apr 08, 2023",
    endDate: "Leading text",
    status: "Accepted",
    price: "NGN 65,000",
    actions: "Leading text",
  },
  {
    vehicle: "Toyota Camry 2021",
    guestName: "Obinna Anozie",
    bookingId: "BKG-6789-KL56",
    bookingType: "Leading text",
    duration: "3 days",
    startDate: "Apr 07, 2023",
    endDate: "Apr 07, 2023",
    status: "Accepted",
    price: "NGN 70,000",
    actions: "Leading text",
  },
  {
    vehicle: "Mercedes-Benz C-Class 2019",
    guestName: "Adebayo Olatunji",
    bookingId: "BKG-3851-ZW76",
    bookingType: "Instant",
    duration: "2 days",
    startDate: "Apr 06, 2023",
    endDate: "Leading text",
    status: "Accepted",
    price: "NGN 50,000",
    actions: "Leading text",
  },
];
